### ISSUE TITLE
On Windows the upnpbridge.xml file was not created

### ISSUE THREAD

**Issue by gbraad** [philippe44/LMS-to-uPnP#36]
On start of `squeeze2upnp.exe` on Windows 10, the file in `C:\ProgramData\Squeezebox\prefs` is not automatically created. I had manually create a file `C:\ProgramData\Squeezebox\prefs\upnpbridge.xml` before this started working.

**Comment by philippe44** [comment]
It's just because no player has been detected. There is no need to create a file manually and adding players in such file will not make them appear in LMS. Players are created in LMS when they are detected by a search, not because they exist in the config file which is here to setup player's parameters once they are detected.

**Comment by philippe44** [comment]
Closed for inactivity
