### ISSUE TITLE
missing dlls issue

### ISSUE THREAD

**Issue by eseb63** [philippe44/LMS-to-uPnP#40]
hello,
i have some trouble to run the upnp bridge on LMS (7.9 on windows 7 32 bits).

i got first a missing libgcc_s_sjlj-1.dll error when clicking on the "Running (squeeze2upnp-win.exe)" checkbox.
i had this dll on my desktop in several versions installed with different products, i placed one of them in this folder: "C:\ProgramData\Squeezebox\Cache\InstalledPlugins\Plugins\UPnPBridge\Bin" and it fixed the issue.

i had next a missing libwinpthread-1.dll, when clicking again on the same checkbox. I did the same operation to fix it.

but i don't know if they have  the good version, and would want to be sure of their right location.

if they are necessary, why these dlls aren't included in the plugin installation process? a licence question?

i don't find the libwinpthread-1.dll on the link you give in the list of dependencies ; i searched on ftp://sourceware.org/pub/pthreads-win32/dll-latest/

and the libgcc_s_sjlj-1.dll is not mentioned in the dependency list.

so could you precise me where to find these 2 dlls and where to put them?

thanks in advance,
eseb63

**Comment by philippe44** [comment]
You are the first one to complain about that AFAIK, so there is something with your installation. These libraries are not required by my windows build

**Comment by eseb63** [comment]
what installation are you talking about? that of lms or that of the plugin? i simply installed LMS 7.9 (with admin rights) then updated it from the web control (7.9.2), and installed the plugin again from the web control but i had to try several times before success (the server didn't restart when i clicked on the "apply" button, or the plugin was not installed after restart).  i had the same problem to update from 1.26 to 1.28.
do you think i should uninstall LMS and install the 7.9.3 version ?

**Comment by philippe44** [comment]
Well, we have made several fixes in 7.9.3, but it's not related to what you are experiencing. When plugins don't install, it's usually because of an issue where with plugins download files being pretty large now, LMS offers a reboot even before actual download has finished. Best is to not click immediately on the "ok", but to take a coffee and then come back a few minutes later. Also, in the case of failure, clean the /ProgramData/squeezeboxserver/Cache/DownloadedPlugins (from memory, check the precise path)

**Comment by eseb63** [comment]
i installed LMS 7.9.3 on a Windows 8.1 system that i almost never used, to be sure having a clean state ; only 4 utilities were installed prior to the LMS install (firewall, etc).

i checked the DownloadedPlugins folder and indeed, the LMS restart dialog pops too quickly, while the download is not ended ;  i noticed also the download was very slow  at 22pm (where is the server ? in the USA?)

anyway, i have exactly the sames error messages than with my windows 7 PC when trying to run or restart the plugin.

i also checked with winmerge the content of the installed plugin folder and the content of the .zip downloaded from sourceforge : they are identical.

excepted sorcery, i don't see why my 2 windows installations (and specially the 8.1 fresh one) could explain these errors ?  did you recently test the plugin install on windows ? the most likely assumption for me is that it has to do with LMS or the plugin ?

**Comment by eseb63** [comment]
might i have a reply?

**Comment by philippe44** [comment]
Well ... it's not that I'm not busy with many things, please be patient especially as not a lot of others have that issue. I'm using a Pi & Windows LMS together, so yes I use Windows. 

Now, there is probably something missing due to a combination of dlls, but it does not happen on most installations. I had to change libeay32.dll a while ago to support Win10 and the version I've used might be the problem, I'll see if there is something I can investigate there.

**Comment by eseb63** [comment]
Any news? did you have some time to investigate ?

**Comment by philippe44** [comment]
I did not find a solution to that issue and have not heard other reports
