### ISSUE TITLE
UPnP / DLNA bridge player profile is not saved

### ISSUE THREAD

**Issue by Andreas221988** [philippe44/LMS-to-uPnP#53]
Hi

 I have several SONOS speakers, they are all found via UPNP, unfortunately I cannot assign the SONOS profile to them.

 I always choose SONOS, click Apply and then apply ... Unfortunately, it doesn't apply the changes and the field remains empty ...

 What could be the reason?

**Comment by philippe44** [comment]
I'm not sure I'm following. Some fields remain empty because the profile only enforce the critical parameters that *must* be overloaded for a given player, it's not a full set, on purpose.

For example, on Sonos, you'll see that codecs add a "-ogg" statement. It means remove ogg no matter what because ogg does not work properly with Sonos. Now, if your global codecs profile does not have flac (for some reason you don't want to send flac to any of your players), the Sonos profile will not force it, it remains your choice at the highest level.

There is no perfect logic, but the one I've selected is that profile are just the "must enforce" parameters

**Comment by Andreas221988** [comment]
is it normal that this field remains empty despite a Sonos profile?

![image](https://user-images.githubusercontent.com/89093822/129866652-86beb507-b158-44b8-ad4e-201a875ae455.jpeg)

**Comment by philippe44** [comment]
Yes it is. You don't have here the profile that is currently applied, but the profile you want to apply - it's a set once and go away
